repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: "v0.0.267"
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

#- repo: https://github.com/psf/black
#  rev: 23.1.0
#  hooks:
#  - id: black

#- repo: https://github.com/PyCQA/isort
#  rev: 5.12.0
#  hooks:
#  - id: isort
#    files: \.py$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
  - id: mypy
    args: ["--pretty", "--show-error-codes"]
    additional_dependencies: [
        'nox',
        'pytest',
    ]
